# baseURL
@baseURL = http://localhost:8001

###
# User Signup
POST {{ baseURL }}/createBusiness
Content-Type: application/json

{
  "name": "My Business",
  "logo": "some logo",
  "domain": "my domain",
  "isMultipleLocationEnabled": true
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password"
}
